# Based on http://lmjohns3.com/2015/06/using-travis-ci-with-miniconda-scipy-and-nose.html
# Tweaked to specify versions on everything for stability
language: python
python:
  - "2.7"
cache: apt
addons:
  apt:
    packages:
    - libatlas-dev
    - libatlas-base-dev
    - liblapack-dev
    - gfortran
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda2-4.2.12-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  # Prefer stability to having the latest
  #- conda update --yes conda
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION cython==0.25.2 numpy=1.11.2
  - pip install clodius==0.3.2
  - pip install -r requirements.txt
  - python manage.py migrate
  - python manage.py runserver localhost:8000

script:
  - set -e
  - wget -O -P data/ https://s3.amazonaws.com/pkerp/public/dixon2012-h1hesc-hindiii-allreps-filtered.1000kb.multires.cool
  - wget -O -P data/ https://s3.amazonaws.com/pkerp/public/wgEncodeCaltechRnaSeqHuvecR1x75dTh1014IlnaPlusSignalRep2.hitile
  - wget -O -P data/ https://s3.amazonaws.com/pkerp/public/gene_annotations.short.db
  - python manage.py test tilesets
